### ISSUE TITLE
Invalid id: null - null

### ISSUE THREAD

**Issue by klauswuestefeld** [clj-commons/vizdeps#8]
Hi, I'm getting this error running `lein vizdeps` on my project. Seems vizdeps needs to sanitize some ids before calling Dorothy.

java.lang.RuntimeException: Invalid id: null - null
 at dorothy.core$error.invokeStatic (core.clj:201)
    dorothy.core$error.doInvoke (core.clj:199)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    dorothy.core$escape_id.invokeStatic (core.clj:485)
    dorothy.core$escape_id.invoke (core.clj:476)
    dorothy.core$dot_STAR__attrs$iter__819__823$fn__824.invoke (core.clj:502)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:709)
    clojure.core$next__5371.invokeStatic (core.clj:64)
    clojure.string$join.invokeStatic (string.clj:191)
    clojure.string$join.invoke (string.clj:180)
    dorothy.core$dot_STAR__attrs.invokeStatic (core.clj:499)
    dorothy.core$dot_STAR__attrs.invoke (core.clj:498)
    dorothy.core$dot_STAR__trailing_attrs.invokeStatic (core.clj:506)
    dorothy.core$dot_STAR__trailing_attrs.invoke (core.clj:504)
    dorothy.core$eval862$fn__864.invoke (core.clj:521)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    clojure.core$map$fn__5851.invoke (core.clj:2753)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.RT.seq (RT.java:531)
    clojure.core$seq__5387.invokeStatic (core.clj:137)
    clojure.core$interleave$fn__6215.invoke (core.clj:4316)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:709)
    clojure.core$next__5371.invokeStatic (core.clj:64)
    clojure.core$str$fn__5451.invoke (core.clj:557)
    clojure.core$str.invokeStatic (core.clj:555)
    clojure.core$str.doInvoke (core.clj:544)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    dorothy.core$dot_STAR__statements.invokeStatic (core.clj:490)
    dorothy.core$dot_STAR__statements.invoke (core.clj:489)
    dorothy.core$eval871$fn__873.invoke (core.clj:536)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    dorothy.core$dot.invokeStatic (core.clj:557)
    dorothy.core$dot.invoke (core.clj:538)
    leiningen.vizdeps$build_dot.invokeStatic (vizdeps.clj:286)
    leiningen.vizdeps$build_dot.invoke (vizdeps.clj:284)
    leiningen.vizdeps$vizdeps.invokeStatic (vizdeps.clj:312)
    leiningen.vizdeps$vizdeps.doInvoke (vizdeps.clj:304)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__6592.doInvoke (main.clj:284)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__6681.invoke (main.clj:452)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)

Evironment:
Leiningen 2.9.1 on Java 1.8.0_275 OpenJDK 64-Bit Server VM

This is a great project, by the way. Keep it up!

**Comment by slipset** [comment]
Hi, 

I just pulled down `walmartlabs/vizdeps 0.2.0` and ran it on a project of mine, and it seems to work nicely.
Do you have a minimal repro you could share?

Erik.

**Comment by klauswuestefeld** [comment]
Nope. It is covered by an NDA. But the error is pretty clear from the stack
and the code. Simply replacing null ids with the string "null", before
calling Dorothy, should be enough as a first step.

**Comment by hlship** [comment]
Please attach a reproducible case and re-open.
